/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIdRouteImport } from './routes/student.$id'
import { Route as AuthenticatedAdmissionsRouteImport } from './routes/_authenticated/admissions'
import { Route as AuthenticatedAdmissionRouteImport } from './routes/_authenticated/admission'
import { Route as ApiPlutoSplatRouteImport } from './routes/api/pluto/$'
import { Route as AuthenticatedAdmissionIdEditRouteImport } from './routes/_authenticated/admission.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIdRoute = StudentIdRouteImport.update({
  id: '/student/$id',
  path: '/student/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdmissionsRoute = AuthenticatedAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdmissionRoute = AuthenticatedAdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPlutoSplatRoute = ApiPlutoSplatRouteImport.update({
  id: '/api/pluto/$',
  path: '/api/pluto/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdmissionIdEditRoute =
  AuthenticatedAdmissionIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedAdmissionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admission': typeof AuthenticatedAdmissionRouteWithChildren
  '/admissions': typeof AuthenticatedAdmissionsRoute
  '/student/$id': typeof StudentIdRoute
  '/api/pluto/$': typeof ApiPlutoSplatRoute
  '/admission/$id/edit': typeof AuthenticatedAdmissionIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admission': typeof AuthenticatedAdmissionRouteWithChildren
  '/admissions': typeof AuthenticatedAdmissionsRoute
  '/student/$id': typeof StudentIdRoute
  '/api/pluto/$': typeof ApiPlutoSplatRoute
  '/admission/$id/edit': typeof AuthenticatedAdmissionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admission': typeof AuthenticatedAdmissionRouteWithChildren
  '/_authenticated/admissions': typeof AuthenticatedAdmissionsRoute
  '/student/$id': typeof StudentIdRoute
  '/api/pluto/$': typeof ApiPlutoSplatRoute
  '/_authenticated/admission/$id/edit': typeof AuthenticatedAdmissionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admission'
    | '/admissions'
    | '/student/$id'
    | '/api/pluto/$'
    | '/admission/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admission'
    | '/admissions'
    | '/student/$id'
    | '/api/pluto/$'
    | '/admission/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admission'
    | '/_authenticated/admissions'
    | '/student/$id'
    | '/api/pluto/$'
    | '/_authenticated/admission/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  StudentIdRoute: typeof StudentIdRoute
  ApiPlutoSplatRoute: typeof ApiPlutoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/$id': {
      id: '/student/$id'
      path: '/student/$id'
      fullPath: '/student/$id'
      preLoaderRoute: typeof StudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admissions': {
      id: '/_authenticated/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AuthenticatedAdmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admission': {
      id: '/_authenticated/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AuthenticatedAdmissionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/pluto/$': {
      id: '/api/pluto/$'
      path: '/api/pluto/$'
      fullPath: '/api/pluto/$'
      preLoaderRoute: typeof ApiPlutoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admission/$id/edit': {
      id: '/_authenticated/admission/$id/edit'
      path: '/$id/edit'
      fullPath: '/admission/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdmissionIdEditRouteImport
      parentRoute: typeof AuthenticatedAdmissionRoute
    }
  }
}

interface AuthenticatedAdmissionRouteChildren {
  AuthenticatedAdmissionIdEditRoute: typeof AuthenticatedAdmissionIdEditRoute
}

const AuthenticatedAdmissionRouteChildren: AuthenticatedAdmissionRouteChildren =
  {
    AuthenticatedAdmissionIdEditRoute: AuthenticatedAdmissionIdEditRoute,
  }

const AuthenticatedAdmissionRouteWithChildren =
  AuthenticatedAdmissionRoute._addFileChildren(
    AuthenticatedAdmissionRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdmissionRoute: typeof AuthenticatedAdmissionRouteWithChildren
  AuthenticatedAdmissionsRoute: typeof AuthenticatedAdmissionsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdmissionRoute: AuthenticatedAdmissionRouteWithChildren,
  AuthenticatedAdmissionsRoute: AuthenticatedAdmissionsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  StudentIdRoute: StudentIdRoute,
  ApiPlutoSplatRoute: ApiPlutoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
